title: Nyra
email: your-email@example.com

description: >-
  Security writeups and smart contract research.

baseurl: "/myblog"
url: "https://samireddinikhila.github.io/myblog/"


plugins:
  - jekyll-feed

markdown: kramdown
highlighter: none

sass:
  style: compressed

include:
  - assets/css

collections:
  writeups:
    output: true
    permalink: /writeups/:title/
